# Generated by Django 4.2 on 2023-06-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "boardNum",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="글 번호"
                    ),
                ),
                ("boardType", models.CharField(max_length=10, verbose_name="게시판 타입")),
                ("title", models.TextField(verbose_name="글 제목")),
                ("content", models.TextField(verbose_name="글 내용")),
                (
                    "writeDate",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "modifyDate",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일시"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="아이디",
                    ),
                ),
                ("password", models.CharField(max_length=20, verbose_name="비밀번호")),
                ("nickname", models.CharField(max_length=16, verbose_name="닉네임")),
                ("zonecode", models.CharField(max_length=5, verbose_name="우편번호")),
                ("address", models.TextField(verbose_name="주소")),
                ("email", models.TextField(null=True, verbose_name="이메일")),
                (
                    "phone",
                    models.CharField(max_length=13, null=True, verbose_name="전화번호"),
                ),
                (
                    "profileImage",
                    models.ImageField(
                        null=True, upload_to="profile", verbose_name="썸네일"
                    ),
                ),
                (
                    "registerDate",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                (
                    "modifyDate",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "commentNum",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="댓글 번호"
                    ),
                ),
                ("content", models.TextField(verbose_name="글 내용")),
                (
                    "writeDate",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "modifyDate",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일시"),
                ),
                (
                    "boardNum",
                    models.ForeignKey(
                        db_column="boardNum",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="batta.board",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        db_column="username",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="batta.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="board",
            name="username",
            field=models.ForeignKey(
                db_column="username",
                on_delete=django.db.models.deletion.CASCADE,
                to="batta.member",
            ),
        ),
    ]
